language: java
jdk:
    - oraclejdk8
sudo: true
install:
      - . $HOME/.nvm/nvm.sh
      - nvm install stable
      - nvm use stable

before_script:
    cd ui && npm install

script:
    - maven test
    - cd ui && npm test
